# Generated by Django 2.2.15 on 2020-11-12 15:27

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default=account.models.picture, max_length=255, null=True, upload_to=''),
        ),
    ]
